/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package principalinventario;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.RandomAccessFile;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
 import sun.util.BuddhistCalendar;

/**
 *
 * @author LeonarPC
 */
public class gestionInventario extends javax.swing.JFrame {

    private String nombrearchivo;
    public pintar objPintar;

    /**
     * Creates new form gestionInventario
     */
    public gestionInventario() {
        initComponents();
        objPintar=new pintar();
        pintarEstadisticas.getContentPane().add(objPintar);
        
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        agregarProductos = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nombreProducto = new javax.swing.JTextField();
        tipoProducto = new javax.swing.JComboBox();
        codigoProducto = new javax.swing.JTextField();
        precioProducto = new javax.swing.JTextField();
        cantidadProducto = new javax.swing.JTextField();
        descripcionProducto = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        modificarProductos = new javax.swing.JFrame();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        nombreProducto1 = new javax.swing.JTextField();
        tipoProducto1 = new javax.swing.JComboBox();
        codigoProducto1 = new javax.swing.JTextField();
        precioProducto1 = new javax.swing.JTextField();
        cantidadProducto1 = new javax.swing.JTextField();
        descripcionProducto1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        buscar = new javax.swing.JFrame();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        buscarCodigo = new javax.swing.JTextField();
        buscarNombre = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        resultadoBusqueda = new javax.swing.JFrame();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        nombreBuscarProducto = new javax.swing.JLabel();
        tipoBuscarProducto = new javax.swing.JLabel();
        codigoBuscarProducto = new javax.swing.JLabel();
        precioBuscarProducto = new javax.swing.JLabel();
        cantidadBuscarProducto = new javax.swing.JLabel();
        descripcionBuscarProducto = new javax.swing.JLabel();
        buscarModificar = new javax.swing.JFrame();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        buscarCodigo1 = new javax.swing.JTextField();
        buscarNombre1 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        buscarEliminar = new javax.swing.JFrame();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        buscarCodigo2 = new javax.swing.JTextField();
        buscarNombre2 = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        pintarEstadisticas = new javax.swing.JFrame();
        jLabel7 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        buscarProducto = new javax.swing.JMenuItem();
        listadoGeneral = new javax.swing.JMenuItem();
        estadisticas = new javax.swing.JMenuItem();
        estadisticasBarras = new javax.swing.JMenuItem();
        estadisticasTorta = new javax.swing.JMenuItem();
        salir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        agregarProducto = new javax.swing.JMenuItem();
        modificarProducto = new javax.swing.JMenuItem();
        eliminarProducto = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        creditos = new javax.swing.JMenuItem();
        ayuda = new javax.swing.JMenuItem();
        recarga = new javax.swing.JMenuItem();

        agregarProductos.setTitle("Modificar Productos");
        agregarProductos.getContentPane().setLayout(null);

        jLabel1.setText("Nombre del Producto");
        agregarProductos.getContentPane().add(jLabel1);
        jLabel1.setBounds(46, 28, 100, 14);

        jLabel2.setText("Tipo del Producto");
        agregarProductos.getContentPane().add(jLabel2);
        jLabel2.setBounds(46, 66, 83, 14);

        jLabel3.setText("Codigo del Producto");
        agregarProductos.getContentPane().add(jLabel3);
        jLabel3.setBounds(46, 104, 96, 14);

        jLabel4.setText("Precio del Producto");
        agregarProductos.getContentPane().add(jLabel4);
        jLabel4.setBounds(46, 142, 92, 14);

        jLabel5.setText("Cantidad del Producto");
        agregarProductos.getContentPane().add(jLabel5);
        jLabel5.setBounds(46, 180, 106, 14);

        jLabel6.setText("Descripcion del Producto");
        agregarProductos.getContentPane().add(jLabel6);
        jLabel6.setBounds(46, 218, 117, 14);

        nombreProducto.setText(" ");
        agregarProductos.getContentPane().add(nombreProducto);
        nombreProducto.setBounds(172, 25, 69, 20);

        tipoProducto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Carnes", "Cereales", "Granos", "Frutas y verduras", "Frutas", "Lácteos", "Limpieza Doméstica", "Automotriz", "Agua", "Jugos", "Sodas", "Sopas", "Ferretería", "Cuidado y Uso personal", "Cosmeticos", "Utensilios", "Herramientas", "Pintura Doméstica", "Harinas", "Pastas", "Arroz", "Charcuteria", "Enlatados", "Papel", "Juguetes", "Electrónicos", "Electrodomesticos", "Linea Blanca", "Linea Marrón", "Vinos", "Cerveza", "Licores", "Panadería", "Aperitivos", "Bebidas", "Panadería" }));
        agregarProductos.getContentPane().add(tipoProducto);
        tipoProducto.setBounds(172, 63, 138, 20);

        codigoProducto.setText(" ");
        agregarProductos.getContentPane().add(codigoProducto);
        codigoProducto.setBounds(172, 101, 69, 20);

        precioProducto.setText(" ");
        agregarProductos.getContentPane().add(precioProducto);
        precioProducto.setBounds(172, 139, 69, 20);

        cantidadProducto.setText(" ");
        agregarProductos.getContentPane().add(cantidadProducto);
        cantidadProducto.setBounds(170, 177, 71, 20);

        descripcionProducto.setText(" ");
        agregarProductos.getContentPane().add(descripcionProducto);
        descripcionProducto.setBounds(170, 220, 68, 20);

        jButton1.setText("Borrar Todo");
        agregarProductos.getContentPane().add(jButton1);
        jButton1.setBounds(206, 298, 89, 23);

        jButton2.setText("Agregar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        agregarProductos.getContentPane().add(jButton2);
        jButton2.setBounds(332, 298, 71, 23);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/principalinventario/imagenes/cesta basica.jpg"))); // NOI18N
        agregarProductos.getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 253, 160, 101);

        modificarProductos.setTitle("Agregar Productos");
        modificarProductos.getContentPane().setLayout(null);

        jLabel9.setText("Nombre del Producto");
        modificarProductos.getContentPane().add(jLabel9);
        jLabel9.setBounds(46, 28, 100, 14);

        jLabel10.setText("Tipo del Producto");
        modificarProductos.getContentPane().add(jLabel10);
        jLabel10.setBounds(46, 66, 83, 14);

        jLabel11.setText("Codigo del Producto");
        modificarProductos.getContentPane().add(jLabel11);
        jLabel11.setBounds(46, 104, 96, 14);

        jLabel12.setText("Precio del Producto");
        modificarProductos.getContentPane().add(jLabel12);
        jLabel12.setBounds(46, 142, 92, 14);

        jLabel13.setText("Cantidad del Producto");
        modificarProductos.getContentPane().add(jLabel13);
        jLabel13.setBounds(46, 180, 106, 14);

        jLabel14.setText("Descripcion del Producto");
        modificarProductos.getContentPane().add(jLabel14);
        jLabel14.setBounds(46, 218, 117, 14);

        nombreProducto1.setEditable(false);
        nombreProducto1.setText(" ");
        modificarProductos.getContentPane().add(nombreProducto1);
        nombreProducto1.setBounds(172, 25, 69, 20);

        tipoProducto1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Carnes", "Cereales", "Granos", "Frutas y verduras", "Frutas", "Lácteos", "Limpieza Doméstica", "Automotriz", "Agua", "Jugos", "Sodas", "Sopas", "Ferretería", "Cuidado y Uso personal", "Cosmeticos", "Utensilios", "Herramientas", "Pintura Doméstica", "Harinas", "Pastas", "Arroz", "Charcuteria", "Enlatados", "Papel", "Juguetes", "Electrónicos", "Electrodomesticos", "Linea Blanca", "Linea Marrón", "Vinos", "Cerveza", "Licores", "Panadería", "Aperitivos", "Bebidas", "Panadería" }));
        modificarProductos.getContentPane().add(tipoProducto1);
        tipoProducto1.setBounds(172, 63, 138, 20);

        codigoProducto1.setEditable(false);
        codigoProducto1.setText(" ");
        modificarProductos.getContentPane().add(codigoProducto1);
        codigoProducto1.setBounds(172, 101, 69, 20);

        precioProducto1.setText(" ");
        modificarProductos.getContentPane().add(precioProducto1);
        precioProducto1.setBounds(172, 139, 69, 20);

        cantidadProducto1.setText(" ");
        modificarProductos.getContentPane().add(cantidadProducto1);
        cantidadProducto1.setBounds(170, 180, 71, 20);

        descripcionProducto1.setText(" ");
        modificarProductos.getContentPane().add(descripcionProducto1);
        descripcionProducto1.setBounds(170, 220, 68, 20);

        jButton3.setText("Borrar Todo");
        modificarProductos.getContentPane().add(jButton3);
        jButton3.setBounds(190, 260, 89, 23);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/principalinventario/imagenes/cesta basica.jpg"))); // NOI18N
        modificarProductos.getContentPane().add(jLabel15);
        jLabel15.setBounds(10, 253, 160, 101);

        jButton5.setText("modificar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        modificarProductos.getContentPane().add(jButton5);
        jButton5.setBounds(300, 260, 100, 23);

        jLabel16.setText("Codigo Producto");

        jLabel17.setText("Nombre Producto");

        buscarCodigo.setText(" ");
        buscarCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarCodigoActionPerformed(evt);
            }
        });

        buscarNombre.setText(" ");

        jButton6.setText("Buscar Producto");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buscarLayout = new javax.swing.GroupLayout(buscar.getContentPane());
        buscar.getContentPane().setLayout(buscarLayout);
        buscarLayout.setHorizontalGroup(
            buscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buscarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(buscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addGap(41, 41, 41)
                .addGroup(buscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton6)
                    .addGroup(buscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(buscarNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                        .addComponent(buscarCodigo)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        buscarLayout.setVerticalGroup(
            buscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buscarLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(buscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(buscarCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(buscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(buscarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        resultadoBusqueda.setTitle("Modificar Productos");
        resultadoBusqueda.getContentPane().setLayout(null);

        jLabel18.setText("Nombre del Producto");
        resultadoBusqueda.getContentPane().add(jLabel18);
        jLabel18.setBounds(46, 28, 100, 14);

        jLabel19.setText("Tipo del Producto");
        resultadoBusqueda.getContentPane().add(jLabel19);
        jLabel19.setBounds(46, 66, 83, 14);

        jLabel20.setText("Codigo del Producto");
        resultadoBusqueda.getContentPane().add(jLabel20);
        jLabel20.setBounds(46, 104, 96, 14);

        jLabel21.setText("Precio del Producto");
        resultadoBusqueda.getContentPane().add(jLabel21);
        jLabel21.setBounds(46, 142, 92, 14);

        jLabel22.setText("Cantidad del Producto");
        resultadoBusqueda.getContentPane().add(jLabel22);
        jLabel22.setBounds(46, 180, 106, 14);

        jLabel23.setText("Descripcion del Producto");
        resultadoBusqueda.getContentPane().add(jLabel23);
        jLabel23.setBounds(46, 218, 117, 14);

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/principalinventario/imagenes/cesta basica.jpg"))); // NOI18N
        resultadoBusqueda.getContentPane().add(jLabel24);
        jLabel24.setBounds(10, 253, 160, 101);

        nombreBuscarProducto.setText("Nombre del Producto");
        resultadoBusqueda.getContentPane().add(nombreBuscarProducto);
        nombreBuscarProducto.setBounds(180, 30, 100, 14);

        tipoBuscarProducto.setText("Tipo del Producto");
        resultadoBusqueda.getContentPane().add(tipoBuscarProducto);
        tipoBuscarProducto.setBounds(180, 70, 83, 14);

        codigoBuscarProducto.setText("Codigo del Producto");
        resultadoBusqueda.getContentPane().add(codigoBuscarProducto);
        codigoBuscarProducto.setBounds(180, 110, 96, 14);

        precioBuscarProducto.setText("Precio del Producto");
        resultadoBusqueda.getContentPane().add(precioBuscarProducto);
        precioBuscarProducto.setBounds(180, 150, 92, 14);

        cantidadBuscarProducto.setText("Cantidad del Producto");
        resultadoBusqueda.getContentPane().add(cantidadBuscarProducto);
        cantidadBuscarProducto.setBounds(180, 180, 106, 14);

        descripcionBuscarProducto.setText("Descripcion del Producto");
        resultadoBusqueda.getContentPane().add(descripcionBuscarProducto);
        descripcionBuscarProducto.setBounds(180, 210, 117, 14);

        jLabel25.setText("Codigo Producto");

        jLabel26.setText("Nombre Producto");

        buscarCodigo1.setText(" ");
        buscarCodigo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarCodigo1ActionPerformed(evt);
            }
        });

        buscarNombre1.setText(" ");

        jButton7.setText("Buscar Modificar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buscarModificarLayout = new javax.swing.GroupLayout(buscarModificar.getContentPane());
        buscarModificar.getContentPane().setLayout(buscarModificarLayout);
        buscarModificarLayout.setHorizontalGroup(
            buscarModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buscarModificarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(buscarModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25)
                    .addComponent(jLabel26))
                .addGap(41, 41, 41)
                .addGroup(buscarModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton7)
                    .addGroup(buscarModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(buscarNombre1, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                        .addComponent(buscarCodigo1)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        buscarModificarLayout.setVerticalGroup(
            buscarModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buscarModificarLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(buscarModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(buscarCodigo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(buscarModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(buscarNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        buscarEliminar.setTitle("Eliminar Producto");

        jLabel27.setText("Codigo Producto");

        jLabel28.setText("Nombre Producto");

        buscarCodigo2.setText(" ");
        buscarCodigo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarCodigo2ActionPerformed(evt);
            }
        });

        buscarNombre2.setText(" ");

        jButton8.setText("Buscar Producto");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buscarEliminarLayout = new javax.swing.GroupLayout(buscarEliminar.getContentPane());
        buscarEliminar.getContentPane().setLayout(buscarEliminarLayout);
        buscarEliminarLayout.setHorizontalGroup(
            buscarEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buscarEliminarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(buscarEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27)
                    .addComponent(jLabel28))
                .addGap(41, 41, 41)
                .addGroup(buscarEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton8)
                    .addGroup(buscarEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(buscarNombre2, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                        .addComponent(buscarCodigo2)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        buscarEliminarLayout.setVerticalGroup(
            buscarEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buscarEliminarLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(buscarEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(buscarCodigo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(buscarEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(buscarNombre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pintarEstadisticasLayout = new javax.swing.GroupLayout(pintarEstadisticas.getContentPane());
        pintarEstadisticas.getContentPane().setLayout(pintarEstadisticasLayout);
        pintarEstadisticasLayout.setHorizontalGroup(
            pintarEstadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 486, Short.MAX_VALUE)
        );
        pintarEstadisticasLayout.setVerticalGroup(
            pintarEstadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 294, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/principalinventario/imagenes/inventarios.png"))); // NOI18N

        jMenu1.setText("Archivo");

        buscarProducto.setText("Buscar Producto");
        buscarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarProductoActionPerformed(evt);
            }
        });
        jMenu1.add(buscarProducto);

        listadoGeneral.setText("Listado General");
        jMenu1.add(listadoGeneral);

        estadisticas.setText("Graficar Estadisticas");
        estadisticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadisticasActionPerformed(evt);
            }
        });
        jMenu1.add(estadisticas);

        estadisticasBarras.setText("Graficar Estadisticas Barras por Libreria");
        jMenu1.add(estadisticasBarras);

        estadisticasTorta.setText("Graficar Estadisticas Torta por Libreria");
        estadisticasTorta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadisticasTortaActionPerformed(evt);
            }
        });
        jMenu1.add(estadisticasTorta);

        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        jMenu1.add(salir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edición");

        jMenu3.setText("Productos");

        agregarProducto.setText("Agregar Producto");
        agregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarProductoActionPerformed(evt);
            }
        });
        jMenu3.add(agregarProducto);

        modificarProducto.setText("Modificar Producto");
        modificarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarProductoActionPerformed(evt);
            }
        });
        jMenu3.add(modificarProducto);

        eliminarProducto.setText("Eliminar Producto");
        eliminarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarProductoActionPerformed(evt);
            }
        });
        jMenu3.add(eliminarProducto);

        jMenu2.add(jMenu3);

        jMenuBar1.add(jMenu2);

        jMenu5.setText("Ayuda");
        jMenu5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu5ActionPerformed(evt);
            }
        });

        creditos.setText("Creditos");
        creditos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditosActionPerformed(evt);
            }
        });
        jMenu5.add(creditos);

        ayuda.setText("Ayuda");
        jMenu5.add(ayuda);

        recarga.setText("Recarga automática");
        recarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recargaActionPerformed(evt);
            }
        });
        jMenu5.add(recarga);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 630, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 459, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void agregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarProductoActionPerformed
        // TODO add your handling code here:
        agregarProductos.setBounds(0, 0, 500, 500);
        agregarProductos.setLocationRelativeTo(null);
        agregarProductos.setVisible(true);
    }//GEN-LAST:event_agregarProductoActionPerformed

    private void estadisticasTortaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadisticasTortaActionPerformed
        // TODO add your handling code here:
        
        
    DefaultCategoryDataset dataset = new DefaultCategoryDataset();
    int cantPro = objPintar.cantidadProductos();
    int[][] indCantProd = new int[2][cantPro];
     objPintar.cargarVectProd(indCantProd);

    for (int i = 0; i < cantPro; i++) {

        dataset.addValue(indCantProd[1][i], ("Prod:" + (indCantProd[0][i])), "ID:" + indCantProd[1][i]);

    }


    //Estadisticas_libreria.setLayout(null);
    JFreeChart chart = ChartFactory.createBarChart(
            "Cantidad de productos en el almacen",
            "Productos",
            "Cantidad",
            dataset,
            PlotOrientation.VERTICAL,
            true,
            true,
            true);
    ChartPanel chartPanel = new ChartPanel(chart, true);
    pintarEstadisticas.setLayout(null);
    pintarEstadisticas.setContentPane((chartPanel));
    pintarEstadisticas.setLocationRelativeTo(null);//centrar pantalla
    // Estadisticas_libreria.pack();
    pintarEstadisticas.setVisible(true);
    }//GEN-LAST:event_estadisticasTortaActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void creditosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditosActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Programado por: ", "Titulo de la ventana", 1);
    }//GEN-LAST:event_creditosActionPerformed

    private void modificarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarProductoActionPerformed
        // TODO add your handling code here:
        buscarModificar.setBounds(150, 150, 400, 300);
        buscarModificar.setVisible(true);
    }//GEN-LAST:event_modificarProductoActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {  // TODO add your handling code here:
            File f = new File(nombrearchivo);
            f.delete();
            if (!f.exists()) {
                FileWriter escribir = new FileWriter(f);
                escribir.write(nombreProducto1.getText());
                escribir.write(System.getProperty("line.separator"));
                escribir.write(tipoProducto1.getSelectedItem().toString());
                escribir.write(System.getProperty("line.separator"));
                escribir.write(codigoProducto1.getText());
                escribir.write(System.getProperty("line.separator"));
                escribir.write(precioProducto1.getText());
                escribir.write(System.getProperty("line.separator"));
                escribir.write(cantidadProducto1.getText());
                escribir.write(System.getProperty("line.separator"));
                escribir.write(descripcionProducto1.getText());
                escribir.close();
                JOptionPane.showMessageDialog(this, "modificacion satisfactoria", "modificacion", 1);
                modificarProductos.setVisible(false);
            }
        } catch (IOException ex) {
            Logger.getLogger(gestionInventario.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton5ActionPerformed

    private void buscarCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarCodigoActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        try {
            int cod = Integer.parseInt(buscarCodigo.getText().trim());
            //sirve para convertir un string a solo entero
            if (buscarCodigo(cod)) {
                FileReader leer = null;
                File f = new File("productos\\" + buscarNombreProducto(cod) + ".txt");

                leer = new FileReader(f);

                BufferedReader bufLeer = new BufferedReader(leer);
                nombreBuscarProducto.setText(bufLeer.readLine());//leemos el nombre del prodcuto
                tipoBuscarProducto.setText(bufLeer.readLine());//leemos tipo del producto
                codigoBuscarProducto.setText(bufLeer.readLine());//leemos el codigo del producto
                precioBuscarProducto.setText(bufLeer.readLine());//leemos el precio del producto
                cantidadBuscarProducto.setText(bufLeer.readLine());//leemos la cantidad del producto
                descripcionBuscarProducto.setText(bufLeer.readLine());//leemos la descripcion del producto
                bufLeer.close();
                leer.close();
                resultadoBusqueda.setBounds(150, 150, 400, 400);
                resultadoBusqueda.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "No se encontro el producto ", "Busqueda de Productos", 0);
            }
        } catch (FileNotFoundException ex) {
        } catch (IOException ex) {
        }
    }//GEN-LAST:event_jButton6ActionPerformed
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int cod = Integer.parseInt(codigoProducto.getText().trim());

        try {
            if (!buscarCodigo(cod) && !buscarNombreProducto(nombreProducto.getText().trim())) {
                File f = new File("productos\\" + nombreProducto.getText() + ".txt");
                if (!f.exists()) {
                    //sino existe creamos el archivo inicial
                    f.createNewFile();
                }
                FileWriter escribir = new FileWriter(f);
                escribir.write(nombreProducto.getText());
                escribir.write(System.getProperty("line.separator"));
                escribir.write(tipoProducto.getSelectedItem().toString());
                escribir.write(System.getProperty("line.separator"));
                escribir.write(codigoProducto.getText());
                escribir.write(System.getProperty("line.separator"));
                escribir.write(precioProducto.getText());
                escribir.write(System.getProperty("line.separator"));
                escribir.write(cantidadProducto.getText());
                escribir.write(System.getProperty("line.separator"));
                escribir.write(descripcionProducto.getText());
                escribir.close();
            } else {
                JOptionPane.showMessageDialog(this, "El producto ya existe", "Agregar Productos", 0);
            }
        } catch (IOException ex) {
        }
    }//GEN-LAST:event_jButton2ActionPerformed
    private void jMenu5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu5ActionPerformed

    private void recargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recargaActionPerformed
        // TODO add your handling code here:
        insertarAuto();
    }//GEN-LAST:event_recargaActionPerformed

    private void buscarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarProductoActionPerformed
        // TODO add your handling code here:
        buscar.setBounds(150, 150, 400, 300);
        buscar.setVisible(true);
    }//GEN-LAST:event_buscarProductoActionPerformed

    private void buscarCodigo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarCodigo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarCodigo1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        try {
            int cod = Integer.parseInt(buscarCodigo1.getText().trim());
            //sirve para convertir un string a solo entero
            if (buscarCodigo(cod)) {

                FileReader leer = null;
                nombrearchivo = "productos\\" + buscarNombreProducto(cod) + ".txt";

                File f = new File(nombrearchivo);

                leer = new FileReader(f);

                BufferedReader bufLeer = new BufferedReader(leer);
                nombreProducto1.setText(bufLeer.readLine());//leemos el nombre del prodcuto
                //tipoProducto1.setText(bufLeer.readLine());//leemos tipo del producto
                bufLeer.readLine();
                codigoProducto1.setText(bufLeer.readLine());//leemos el codigo del producto
                precioProducto1.setText(bufLeer.readLine());//leemos el precio del producto
                cantidadProducto1.setText(bufLeer.readLine());//leemos la cantidad del producto
                descripcionProducto1.setText(bufLeer.readLine());//leemos la descripcion del producto
                bufLeer.close();
                leer.close();

                modificarProductos.setBounds(0, 0, 500, 500);
                modificarProductos.setLocationRelativeTo(null);
                modificarProductos.setVisible(true);

            }
        } catch (IOException ex) {
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void buscarCodigo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarCodigo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarCodigo2ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        try {  // TODO add your handling code here:
            String cad = buscarNombreProducto(Integer.parseInt(buscarCodigo2.getText().trim()));
            //aqui debemos comparar que el nombre del archivo sea diferente de "ninguno"
            if (cad.compareToIgnoreCase("ninguno") != 0) {
                int opcion = JOptionPane.showConfirmDialog(this, "¿Seguro que Desea Borrar el Producto: "
                        + cad + " ?", "Borrado", JOptionPane.YES_NO_OPTION);
                if (opcion == JOptionPane.OK_OPTION) {
                    File f = new File("productos\\indices.txt");
                    RandomAccessFile archivoAleatorio = new RandomAccessFile(f, "rw");
                    //BufferedReader archivoProductoLeer = new BufferedReader( );
                    String strLinea = archivoAleatorio.readLine();
                    String cortarPalabras[];
                    long tomamosPosicionFinal = 0, tomamosPosicionInicial = 0;
                    boolean enc = false;

                    // Se Lee el archivo linea por linea
                    while (strLinea != null) {
                        cortarPalabras = strLinea.split(";");//por cada linea leida cortamos
                        if (cortarPalabras[0]!=null && cortarPalabras[0].charAt(0)!='\0' && cortarPalabras[1].compareTo(cad) == 0) {//comparamos el corte con el nombre
                            tomamosPosicionFinal = archivoAleatorio.getChannel().position();//leemos posicionfinal
                            enc = true;//indicamos que la encontramos
                            break;
                        }
                        tomamosPosicionInicial = archivoAleatorio.getChannel().position();//leemos inicio de cadena
                        strLinea = archivoAleatorio.readLine();//leemos la siguiente linea del archivo indice
                    }

                    if (enc) {
                        archivoAleatorio.seek(tomamosPosicionInicial); // el menos 1 es para no borrar el salto de linea no el retorno de carro
                        //el Seek nos ubica en una posicion en Bytes dentro del archivo
                        byte[] byt = new byte[(int) (tomamosPosicionFinal - tomamosPosicionInicial) - 2];
                        //byt= "HOLA CASA".getBytes();
                        archivoAleatorio.write(byt); //escribimos un byte vacio en esa posicion

                        archivoAleatorio.close();//cerramos el archivo indice para guardar los cambios
                        //damos memoria a file nuevamente para usar otra direccion con un archivo en esa direccion
                        f = new File("productos/" + cad + ".txt"); //seleccionado el archivo
                        f.delete();//lo borramos fisicamente...
                    }
                }

            } else {
                JOptionPane.showMessageDialog(this, "El producto NO existe", "Eliminar Productos", 0);
            }
        } catch (IOException ex) {
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void eliminarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarProductoActionPerformed
        // TODO add your handling code here:
        buscarEliminar.setBounds(150, 150, 400, 300);
        buscarEliminar.setVisible(true);
    }//GEN-LAST:event_eliminarProductoActionPerformed

    private void estadisticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadisticasActionPerformed
        // TODO add your handling code here:
        pintarEstadisticas.setBounds(0,0, 600,400);
        pintarEstadisticas.setVisible(true);
    }//GEN-LAST:event_estadisticasActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem agregarProducto;
    private javax.swing.JFrame agregarProductos;
    private javax.swing.JMenuItem ayuda;
    private javax.swing.JFrame buscar;
    private javax.swing.JTextField buscarCodigo;
    private javax.swing.JTextField buscarCodigo1;
    private javax.swing.JTextField buscarCodigo2;
    private javax.swing.JFrame buscarEliminar;
    private javax.swing.JFrame buscarModificar;
    private javax.swing.JTextField buscarNombre;
    private javax.swing.JTextField buscarNombre1;
    private javax.swing.JTextField buscarNombre2;
    private javax.swing.JMenuItem buscarProducto;
    private javax.swing.JLabel cantidadBuscarProducto;
    private javax.swing.JTextField cantidadProducto;
    private javax.swing.JTextField cantidadProducto1;
    private javax.swing.JLabel codigoBuscarProducto;
    private javax.swing.JTextField codigoProducto;
    private javax.swing.JTextField codigoProducto1;
    private javax.swing.JMenuItem creditos;
    private javax.swing.JLabel descripcionBuscarProducto;
    private javax.swing.JTextField descripcionProducto;
    private javax.swing.JTextField descripcionProducto1;
    private javax.swing.JMenuItem eliminarProducto;
    private javax.swing.JMenuItem estadisticas;
    private javax.swing.JMenuItem estadisticasBarras;
    private javax.swing.JMenuItem estadisticasTorta;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem listadoGeneral;
    private javax.swing.JMenuItem modificarProducto;
    private javax.swing.JFrame modificarProductos;
    private javax.swing.JLabel nombreBuscarProducto;
    private javax.swing.JTextField nombreProducto;
    private javax.swing.JTextField nombreProducto1;
    private javax.swing.JFrame pintarEstadisticas;
    private javax.swing.JLabel precioBuscarProducto;
    private javax.swing.JTextField precioProducto;
    private javax.swing.JTextField precioProducto1;
    private javax.swing.JMenuItem recarga;
    private javax.swing.JFrame resultadoBusqueda;
    private javax.swing.JMenuItem salir;
    private javax.swing.JLabel tipoBuscarProducto;
    private javax.swing.JComboBox tipoProducto;
    private javax.swing.JComboBox tipoProducto1;
    // End of variables declaration//GEN-END:variables

    public void insertarAuto() {
        try {
            File f = new File("productos/indices.txt");
            if (!f.exists()) {
                //sino existe creamos el archivo inicial
                f.createNewFile();
            }

            FileWriter archivoProductoCrear = new FileWriter("productos/" + "Peras" + ".txt");
            FileWriter indices = new FileWriter(f);

            archivoProductoCrear.write("Peras");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("Frutas y verduras");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("1");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("25");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("659");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("No Disponible");
            archivoProductoCrear.close();
            indices.write("1;");
            indices.write("Peras");
            indices.write(System.getProperty("line.separator"));



            archivoProductoCrear = new FileWriter("productos/" + "Manzanas" + ".txt");
            archivoProductoCrear.write("Manzanas");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("Frutas y verduras");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("2");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("19");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("635");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("No Disponible");
            archivoProductoCrear.close();
            indices.write("2;");
            indices.write("Manzanas");
            indices.write(System.getProperty("line.separator"));

            archivoProductoCrear = new FileWriter("productos/" + "Platanos" + ".txt");
            archivoProductoCrear.write("Platanos");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("Frutas y verduras");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("3");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("49");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("768");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("No Disponible");
            archivoProductoCrear.close();
            indices.write("3;");
            indices.write("Platanos");
            indices.write(System.getProperty("line.separator"));

            archivoProductoCrear = new FileWriter("productos/" + "Lechuga" + ".txt");
            archivoProductoCrear.write("Lechuga");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("Frutas y verduras");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("4");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("6");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("748");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("No Disponible");
            archivoProductoCrear.close();
            indices.write("4;");
            indices.write("Lechuga");
            indices.write(System.getProperty("line.separator"));

            archivoProductoCrear = new FileWriter("productos/" + "Tomates" + ".txt");
            archivoProductoCrear.write("Tomates");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("Frutas y verduras");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("5");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("37");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("984");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("No Disponible");
            archivoProductoCrear.close();
            indices.write("5;");
            indices.write("Tomates");
            indices.write(System.getProperty("line.separator"));

            archivoProductoCrear = new FileWriter("productos/" + "Mangos" + ".txt");
            archivoProductoCrear.write("Mangos");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("Frutas y verduras");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("6");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("41");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("766");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("No Disponible");
            archivoProductoCrear.close();
            indices.write("6;");
            indices.write("Mangos");
            indices.write(System.getProperty("line.separator"));

            archivoProductoCrear = new FileWriter("productos/" + "Apio" + ".txt");
            archivoProductoCrear.write("Apio");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("Frutas y verduras");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("7");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("36");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("757");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("No Disponible");
            archivoProductoCrear.close();
            indices.write("7;");
            indices.write("Apio");
            indices.write(System.getProperty("line.separator"));

            archivoProductoCrear = new FileWriter("productos/" + "Pepinillo" + ".txt");
            archivoProductoCrear.write("Pepinillo");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("Frutas y verduras");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("8");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("13");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("594");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("No Disponible");
            archivoProductoCrear.close();
            indices.write("8;");
            indices.write("Pepinillo");
            indices.write(System.getProperty("line.separator"));

            archivoProductoCrear = new FileWriter("productos/" + "Setas" + ".txt");
            archivoProductoCrear.write("Setas");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("Frutas y verduras");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("9");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("40");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("924");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("No Disponible");
            archivoProductoCrear.close();
            indices.write("9;");
            indices.write("Setas");
            indices.write(System.getProperty("line.separator"));

            archivoProductoCrear = new FileWriter("productos/" + "Leche" + ".txt");
            archivoProductoCrear.write("Leche");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("Lácteos");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("10");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("39");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("626");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("No Disponible");
            archivoProductoCrear.close();
            indices.write("10;");
            indices.write("Leche");
            indices.write(System.getProperty("line.separator"));

            archivoProductoCrear = new FileWriter("productos/" + "Queso" + ".txt");
            archivoProductoCrear.write("Queso");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("Lácteos");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("11");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("6");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("940");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("No Disponible");
            archivoProductoCrear.close();
            indices.write("11;");
            indices.write("Queso");
            indices.write(System.getProperty("line.separator"));

            archivoProductoCrear = new FileWriter("productos/" + "Mantequilla" + ".txt");
            archivoProductoCrear.write("Mantequilla");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("Lácteos");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("12");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("29");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("779");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("No Disponible");
            archivoProductoCrear.close();
            indices.write("12;");
            indices.write("Mantequilla");
            indices.write(System.getProperty("line.separator"));

            archivoProductoCrear = new FileWriter("productos/" + "Requeson" + ".txt");
            archivoProductoCrear.write("Requeson");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("Lácteos");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("13");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("42");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("521");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("No Disponible");
            archivoProductoCrear.close();
            indices.write("13;");
            indices.write("Requeson");
            indices.write(System.getProperty("line.separator"));

            archivoProductoCrear = new FileWriter("productos/" + "Nata" + ".txt");
            archivoProductoCrear.write("Nata");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("Lácteos");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("14");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("22");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("697");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("No Disponible");
            archivoProductoCrear.close();
            indices.write("14;");
            indices.write("Nata");
            indices.write(System.getProperty("line.separator"));

            archivoProductoCrear = new FileWriter("productos/" + "Yogurt" + ".txt");
            archivoProductoCrear.write("Yogurt");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("Lácteos");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("15");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("37");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("797");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("No Disponible");
            archivoProductoCrear.close();
            indices.write("15;");
            indices.write("Yogurt");
            indices.write(System.getProperty("line.separator"));

            archivoProductoCrear = new FileWriter("productos/" + "Carne de ternera" + ".txt");
            archivoProductoCrear.write("Carne de ternera");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("Carnes");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("16");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("26");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("913");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("No Disponible");
            archivoProductoCrear.close();
            indices.write("16;");
            indices.write("Carne de ternera");
            indices.write(System.getProperty("line.separator"));

            archivoProductoCrear = new FileWriter("productos/" + "Carne de ave" + ".txt");
            archivoProductoCrear.write("Carne de ave");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("Carnes");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("17");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("33");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("858");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("No Disponible");
            archivoProductoCrear.close();
            indices.write("17;");
            indices.write("Carne de ave");
            indices.write(System.getProperty("line.separator"));

            archivoProductoCrear = new FileWriter("productos/" + "Jamon" + ".txt");
            archivoProductoCrear.write("Jamon");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("Carnes");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("18");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("31");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("627");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("No Disponible");
            archivoProductoCrear.close();
            indices.write("18;");
            indices.write("Jamon");
            indices.write(System.getProperty("line.separator"));

            archivoProductoCrear = new FileWriter("productos/" + "Carne de cerdo" + ".txt");
            archivoProductoCrear.write("Carne de cerdo");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("Carnes");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("19");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("36");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("673");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("No Disponible");
            archivoProductoCrear.close();
            indices.write("19;");
            indices.write("Carne de cerdo");
            indices.write(System.getProperty("line.separator"));

            archivoProductoCrear = new FileWriter("productos/" + "Carne para el almuerzo" + ".txt");
            archivoProductoCrear.write("Carne para el almuerzo");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("Carnes");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("20");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("36");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("729");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("No Disponible");
            archivoProductoCrear.close();
            indices.write("20;");
            indices.write("Carne para el almuerzo");
            indices.write(System.getProperty("line.separator"));

            archivoProductoCrear = new FileWriter("productos/" + "Soda" + ".txt");
            archivoProductoCrear.write("Soda");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("Bebidas");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("21");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("47");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("660");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("No Disponible");
            archivoProductoCrear.close();
            indices.write("21;");
            indices.write("Soda");
            indices.write(System.getProperty("line.separator"));

            archivoProductoCrear = new FileWriter("productos/" + "Zumo" + ".txt");
            archivoProductoCrear.write("Zumo");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("Bebidas");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("22");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("28");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("997");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("No Disponible");
            archivoProductoCrear.close();
            indices.write("22;");
            indices.write("Zumo");
            indices.write(System.getProperty("line.separator"));

            archivoProductoCrear = new FileWriter("productos/" + "Cafe" + ".txt");
            archivoProductoCrear.write("Cafe");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("Bebidas");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("23");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("44");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("539");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("No Disponible");
            archivoProductoCrear.close();
            indices.write("23;");
            indices.write("Cafe");
            indices.write(System.getProperty("line.separator"));


            archivoProductoCrear = new FileWriter("productos/" + "Te" + ".txt");
            archivoProductoCrear.write("Te");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("Bebidas");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("24");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("15");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("581");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("No Disponible");
            archivoProductoCrear.close();
            indices.write("24;");
            indices.write("Te");
            indices.write(System.getProperty("line.separator"));

            archivoProductoCrear = new FileWriter("productos/" + "Agua" + ".txt");
            archivoProductoCrear.write("Agua");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("Bebidas");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("25");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("2");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("838");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("No Disponible");
            archivoProductoCrear.close();
            indices.write("25;");
            indices.write("Agua");
            indices.write(System.getProperty("line.separator"));

            archivoProductoCrear = new FileWriter("productos/" + "Fideos" + ".txt");
            archivoProductoCrear.write("Fideos");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("Pastas");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("26");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("27");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("895");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("No Disponible");
            archivoProductoCrear.close();
            indices.write("26;");
            indices.write("Fideos");
            indices.write(System.getProperty("line.separator"));

            archivoProductoCrear = new FileWriter("productos/" + "Arroz" + ".txt");
            archivoProductoCrear.write("Arroz");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("Pastas");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("27");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("23");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("955");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("No Disponible");
            archivoProductoCrear.close();
            indices.write("27;");
            indices.write("Arroz");
            indices.write(System.getProperty("line.separator"));


            archivoProductoCrear = new FileWriter("productos/" + "Enlatado naruto" + ".txt");
            archivoProductoCrear.write("Enlatado naruto");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("Sopas");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("28");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("28");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("922");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("No Disponible");
            archivoProductoCrear.close();
            indices.write("28;");
            indices.write("Enlatado naruto");
            indices.write(System.getProperty("line.separator"));

            archivoProductoCrear = new FileWriter("productos/" + "Sopa de sobre" + ".txt");
            archivoProductoCrear.write("Sopa de sobre");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("Sopas");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("29");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("40");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("574");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("No Disponible");
            archivoProductoCrear.close();
            indices.write("29;");
            indices.write("Sopa de sobre");
            indices.write(System.getProperty("line.separator"));

            archivoProductoCrear = new FileWriter("productos/" + "Pan" + ".txt");
            archivoProductoCrear.write("Pan");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("Panadería");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("30");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("13");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("979");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("No Disponible");
            archivoProductoCrear.close();
            indices.write("30;");
            indices.write("Pan");
            indices.write(System.getProperty("line.separator"));

            archivoProductoCrear = new FileWriter("productos/" + "Bollos" + ".txt");
            archivoProductoCrear.write("Bollos");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("Panadería");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("31");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("43");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("538");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("No Disponible");
            archivoProductoCrear.close();
            indices.write("31;");
            indices.write("Bollos");
            indices.write(System.getProperty("line.separator"));

            archivoProductoCrear = new FileWriter("productos/" + "Magdalenas" + ".txt");
            archivoProductoCrear.write("Magdalenas");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("Panadería");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("32");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("10");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("980");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("No Disponible");
            archivoProductoCrear.close();
            indices.write("32;");
            indices.write("Magdalenas");
            indices.write(System.getProperty("line.separator"));

            archivoProductoCrear = new FileWriter("productos/" + "Pastel" + ".txt");
            archivoProductoCrear.write("Pastel");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("Panadería");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("33");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("27");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("654");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("No Disponible");
            archivoProductoCrear.close();
            indices.write("33;");
            indices.write("Pastel");
            indices.write(System.getProperty("line.separator"));


            archivoProductoCrear = new FileWriter("productos/" + "Papas fritas" + ".txt");
            archivoProductoCrear.write("Papas fritas");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("Aperitivos");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("34");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("8");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("727");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("No Disponible");
            archivoProductoCrear.close();
            indices.write("34;");
            indices.write("Papas fritas");
            indices.write(System.getProperty("line.separator"));

            archivoProductoCrear = new FileWriter("productos/" + "Galletas saladas" + ".txt");
            archivoProductoCrear.write("Galletas saladas");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("Aperitivos");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("35");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("38");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("812");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("No Disponible");
            archivoProductoCrear.close();
            indices.write("35;");
            indices.write("Galletas saladas");
            indices.write(System.getProperty("line.separator"));

            archivoProductoCrear = new FileWriter("productos/" + "Helado Fresa" + ".txt");
            archivoProductoCrear.write("Helado Fresa");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("Aperitivos");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("36");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("23");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("550");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("No Disponible");
            archivoProductoCrear.close();
            indices.write("36;");
            indices.write("Helado Fresa");
            indices.write(System.getProperty("line.separator"));

            archivoProductoCrear = new FileWriter("productos/" + "Galletas Maria" + ".txt");
            archivoProductoCrear.write("Galletas Maria");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("Aperitivos");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("37");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("26");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("756");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("No Disponible");
            archivoProductoCrear.close();
            indices.write("37;");
            indices.write("Galletas Maria");
            indices.write(System.getProperty("line.separator"));

            archivoProductoCrear = new FileWriter("productos/" + "Platos de papel" + ".txt");
            archivoProductoCrear.write("Platos de papel");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("Limpieza Doméstica");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("38");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("10");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("953");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("No Disponible");
            archivoProductoCrear.close();
            indices.write("38;");
            indices.write("Platos de papel");
            indices.write(System.getProperty("line.separator"));

            archivoProductoCrear = new FileWriter("productos/" + "Servilletas" + ".txt");
            archivoProductoCrear.write("Servilletas");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("Limpieza Doméstica");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("39");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("30");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("640");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("No Disponible");
            archivoProductoCrear.close();
            indices.write("39;");
            indices.write("Servilletas");
            indices.write(System.getProperty("line.separator"));

            archivoProductoCrear = new FileWriter("productos/" + "Bolsas de basura" + ".txt");
            archivoProductoCrear.write("Bolsas de basura");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("Limpieza Doméstica");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("40");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("13");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("961");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("No Disponible");
            archivoProductoCrear.close();
            indices.write("40;");
            indices.write("Bolsas de basura");
            indices.write(System.getProperty("line.separator"));

            archivoProductoCrear = new FileWriter("productos/" + "Detergente en polvo" + ".txt");
            archivoProductoCrear.write("Detergente en polvo");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("Limpieza Doméstica");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("41");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("5");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("725");
            archivoProductoCrear.write(System.getProperty("line.separator"));
            archivoProductoCrear.write("No Disponible");
            archivoProductoCrear.close();
            indices.write("41;");
            indices.write("Detergente en polvo");
            indices.write(System.getProperty("line.separator"));
            indices.close();
        } catch (IOException ex) {
            System.out.println("algo paso");
        }
    }

    private boolean buscarCodigo(int cod) {
        boolean enc = false;
        try {
            File f = new File("productos\\indices.txt");

            if (!f.exists()) { //preguntamos si no existe el archivo
                f.createNewFile();//si no existe creamos uno vacio
            }
            // lee el archivo caracter a caracter
            FileReader capturarBuffer = new FileReader(f);

            //el buffered reader se usa para leer linea por linea un archivo
            BufferedReader bufLinea = new BufferedReader(capturarBuffer);
            String cadenaLeida = "", vectStr[] = null;
            while ((cadenaLeida = bufLinea.readLine()) != null) {
                vectStr = cadenaLeida.split(";");
                System.out.println("" + vectStr[0]);
                if (Integer.parseInt(vectStr[0]) == cod) {
                    enc = true;
                    break;
                }
            }

        } catch (IOException ex) {
        }

        return enc;
    }

    private String buscarNombreProducto(int cod) {
        boolean enc = false;
        String nomProd = "ninguno";
        try {
            File f = new File("productos\\indices.txt");

            if (!f.exists()) { //preguntamos si no existe el archivo
                f.createNewFile();//si no existe creamos uno vacio
            }
            // lee el archivo caracter a caracter
            FileReader capturarBuffer = new FileReader(f);

            //el buffered reader se usa para leer linea por linea un archivo
            BufferedReader bufLinea = new BufferedReader(capturarBuffer);
            String cadenaLeida = "", vectStr[] = null;
            while ((cadenaLeida = bufLinea.readLine()) != null) {
                vectStr = cadenaLeida.split(";");
               // System.out.println("" + vectStr[1]);
                if (vectStr[0]!=null && vectStr[0].charAt(0)!='\0' && Integer.parseInt(vectStr[0]) == cod) {
                    enc = true;
                    nomProd = vectStr[1];
                    break;
                }
            }

        } catch (IOException ex) {
        }

        return nomProd;
    }

    public boolean buscarNombreProducto(String cad) {
        boolean enc = false;
        try {
            File f = new File("productos\\indices.txt");

            if (!f.exists()) { //preguntamos si no existe el archivo
                f.createNewFile();//si no existe creamos uno vacio
            }
            // lee el archivo caracter a caracter
            FileReader capturarBuffer = new FileReader(f);
            //el buffered reader se usa para leer linea por linea un archivo
            BufferedReader bufLinea = new BufferedReader(capturarBuffer);
            String cadenaLeida = "";
            String vectStr[] = null;
            while ((cadenaLeida = bufLinea.readLine()) != null) {
                vectStr = cadenaLeida.split(";");
                System.out.println("" + vectStr[1]);
                if (vectStr[1].compareToIgnoreCase(cad) == 0) {
                    enc = true;
                    break;
                }
            }
        } catch (IOException ex) {
        }

        return enc;
    }
}
